-- producer table
INSERT INTO producer (producer)
VALUES 
    ('twentieth century fox'),
    ('videocraft international, ltd.'),
    ('michael volpe'),
    ('universal pictures'),
    ('castle rock entertainment'),
    ('michael finnell'),
    ('bill melendez'),
    ('john hughes'),
    ('tim burton'),
    ('jon berg'),
    ('mgm'),
    ('brian desmond hurst'),
    ('joe roth'),
    ('richard donner'),
    ('philip clarke'),
    ('warner bros.'),
    ('rankin/bass productions'),
    ('frank capra'),
    ('entertainment partners ltd.'),
    ('robert zemeckis'),
    ('wilo productions'),
    ('touchstone television'),
    ('aaron russo')
;

-- director table
INSERT INTO director (first_name, last_name)
VALUES 
    ('john', 'mctiernan'),
    ('larry', 'roemer'),
    ('mike', 'clattenburg'),
    ('ron', 'howard'),
    ('robert', 'zemeckis'),
    ('joe', 'dante'),
    ('bill', 'melendez'),
    ('jeremiah', 'chechik'),
    ('henry', 'selick'),
    ('jon', 'favreau'),
    ('bob ', 'clark'),
    ('chris', 'columbus'),
    ('brian', 'hurst'),
    ('tim', 'burton'),
    ('jon', 'turteltaub'),
    ('richard', 'donner'),
    ('carl', 'tibbetts'),
    ('troy ', 'miller'),
    ('chuck', 'jones'),
    ('ben', 'washam'),
    ('jules', 'bass'),
    ('arthur', 'rankin jr.'),
    ('frank', 'capra'),
    ('clive', 'donner'),
    ('simon', 'chong'),
    ('tony', 'gennaro'),
    ('chris', 'song'),
    ('terry', 'hughes'),
    ('john ', 'landis')
;

-- streaming_platform tabel   
INSERT INTO streaming_platform (streaming_platform)
VALUES 
    ('amc plus'),
    ('apple tv'),
    ('crackle'),
    ('crtv'),
    ('directtv'),
    ('disney plus'),
    ('espn plus'),
    ('fandango'),
    ('freevee'),
    ('fubo'),
    ('google play'),
    ('hallmark plus'),
    ('hbo max'),
    ('hulu'),
    ('netflix'),
    ('nosey'),
    ('paramount plus'),
    ('peacock'),
    ('pluto'),
    ('prime video'),
    ('roku'),
    ('sling tv'),
    ('starz'),
    ('tubi'),
    ('youtube')
;

-- actor table
INSERT INTO actor (first_name, last_name, img_url)
VALUES 
('bruce', 'willis',	'bruce_willis.jpg'),
('alan', 'rickman', 'alan_rickman.jpg'),
('alexander', 'godunov', 'alexander_godunov.jpg'),
('bonnie',	'bedelia', 'bonnie_bedelia.jpg'),
('reginald', 'veljohnson', 'reginald_veljohnson.jpg'),
('burl', 'ives', 'burl_ives.jpg'),
('larry', 'mann', 'larry_mann.jpg'),
('billie', 'richards', 'billie_richards.jpg'),
('paul', 'soles', 'paul_soles.jpg'),
('stan', 'francis', 'stan_francis.jpg'),
('jonathan', 'torrens',	'jonathan_torrens.jpg'),
('lucy', 'decoutere', 'lucy_decoutere.jpg'),
('john', 'dunsworth', 'john_dunsworth.jpg'),
('robb', 'wells', 'robb_wells.jpg'),
('john', 'tremblay', 'john_tremblay.jpg'),
('jim', 'carrey', 'jim_carrey.jpg'),
('taylor', 'momsen', 'taylor_momsen.jpg'),
('kelley', 'null', 'kelley.jpg'),
('jeffrey',	'tambor', 'jeffrey_tambor.jpg'),
('christine', 'baranski', 'christine_baranski.jpg'),
('tom',	'hanks', 'tom_hanks.jpg'),
('leslie', 'zemeckis', 'leslie_zemeckis.jpg'),
('eddie', 'deezen', 'eddie_deezen.jpg'),
('nona', 'gaye', 'nona_gaye.jpg'),
('peter', 'scolari', 'peter_scolari.jpg'),
('zach', 'galligan', 'zach_galligan.jpg'),
('phoebe', 'cates', 'phoebe_cates.jpg'),
('hoyt', 'axton', 'hoyt_axton.jpg'),
('polly', 'holliday', 'polly_holliday.JPG'),
('frances', 'mccain', 'frances_mccain.jpg'),
('peter', 'robbins', 'peter_robbins.jpg'),
('christopher', 'shea', 'christopher_shea.jpg'),
('cathy', 'steinberg', 'cathy_steinberg.jpg'),
('tracy', 'stratford', 'tracy_stratford.jpg'),
('bill', 'melendez', 'bill_melendez.jpg'),
('chevy', 'chase', 'chevy_chase.jpg'),
('beverly',	"d'angelo",	'beverly_dangelo.jpg'),
('randy', 'quaid', 'randy_quaid.jpg'),
('william',	'hickey', 'william_hickey.jpg'),
('mae',	'questel', 'mae_questel.jpg'),
('danny', 'elfman', 'danny_elfman.jpg'),
('chris', 'sarandon', 'chris_sarandon.jpg'),
('catherine', "o'hara", 'catherine_ohara.jpg'),
('glenn', 'shadix', 'glenn_shadix.jpg'),
('will', 'ferrell', 'will_ferrell.jpg'),
('james', 'caan', 'james_caan.jpg'),
('zooey', 'deschanel', 'zooey_deschanel.jpg'),
('mary', 'steenburgen', 'mary_steenburgen.jpg'),
('ed', 'asner', 'ed_asner.JPG'),
('melinda', 'dillon', 'melinda_dillon.jpg'),
('darren', 'mcgavin', 'darren_mcgavin.jpg'),
('peter', 'billingsley', 'peter_billingsley.jpg'),
('ian',	'petrella',	'ian_petrella.jpg'),
('scott', 'schwartz', 'scott_schwartz.jpg'),
('macaulay', 'culkin', 'macaulay_culkin.jpg'),
('joe',	'pesci', 'joe_pesci.jpg'),
('daniel', 'stern', 'daniel_stern.jpg'),
('john', 'heard', 'john_heard.jpg'),
('alastair', 'sim', 'alastair_sim.jpg'),
('mervyn', 'johns', 'mervyn_johns.jpg'),
('hermione', 'baddeley', 'hermione_baddley.jpg'),
('jack', 'warner', 'jack_warner.JPG'),
('kathleen', 'harrison', 'kathleen_harrison.jpg'),
('johnny', 'depp', 'johnny_depp.jpg'),
('winona', 'ryder', 'winona_ryder.jpg'),
('dianne', 'wiest', 'diane_wiest.jpg'),
('anthony', 'hall', 'anthony_hall.jpg'),
('kathy', 'baker', 'kathy_baker.jpg'),
('sandra', 'bullock', 'sandra_bullock.jpg'),
('bill', 'pullman', 'bill_pullman.jpg'),
('peter', 'gallagher', 'peter_gallagher.jpg'),
('peter', 'boyle', 'peter_boyle.jpg'),
('glynis', 'johns', 'glynis_johns.jpg'),
('bill', 'murray', 'bill_murray.jpg'),
('karen', 'allen', 'karen_allen.jpg'),
('john', 'forsythe', 'john_forsythe.jpg'),
('bobcat', 'goldthwait', 'bobcat_goldthwait.jpg'),
('carol', 'kane',	'carol_kane.jpg'),
('jon',	'hamm',	'jon_hamm.jpg'),
('rafe', 'spall', 'rafe_spall.jpg'),
('oona', 'chaplin', 'oona_chaplin.jpg'),
('natalia', 'tena', 'natalia_tena.jpg'),
('janet', 'montgomery', 'janet_montgomery.jpg'),
('michael', 'keaton', 'michael_keaton.jpg'),
('kelly', 'preston', 'kelly_preston.jpg'),
('joseph', 'cross', 'joseph_cross.jpg'),
('mark', 'addy', 'mark_addy.jpg'),
('andrew', 'lawrence', 'andrew_lawrence.jpg'),
('boris', 'karloff', 'boris_karloff.jpg'),
('june', 'foray', 'june_foray.JPG'),
('dallas', 'mckennon', 'dallas_mckennon.jpg'),
('thurl', 'ravenscroft', 'thurl_ravenscroft.jpg'),
('walter', 'matthau', 'walter_matthau.jpg'),
('jimmy', 'durante', 'jimmy_durante.jpg'),
('billy', 'de-wolfe', 'billy_dewolfe.jpg'),
('paul', 'frees', 'paul_frees.jpg'),
('jackie', 'vernon', 'jackie_vernon.jpg'),
('james', 'stewart', 'james_stewart.jpg'),
('donna', 'reed', 'donna_reed.jpg'),
('lionel', 'barrymore', 'lionel_barrymore.jpg'),
('thomas', 'mitchell', 'thomas_mitchell.JPG'),
('henry', 'travers', 'henry_travers.jpg'),
('george', 'scott', 'george_scott.JPG'),
('frank ', 'finlay', 'frank_finlay.jpg'),
('david', 'warner', 'david_warner.jpg'),
('susannah', 'york', 'susannah_york.JPG'),
('edward', 'woodward', 'edward_woodward.JPG'),
('gary', 'oldman', 'gary_oldman.jpg'),
('colin', 'firth', 'colin_firth.jpg'),
('bob', 'hoskins', 'bob_hoskins.jpg'),
('robin', 'penn', 'robin_wright_penn.jpg'),
('jon',	'benjamin', 'jon_benjamin.jpg'),
('dan',	'mintz', 'dan_mintz.jpg'),
('eugene', 'mirman', 'eugene_mirman.jpg'),
('john', 'roberts', 'john_roberts.jpg'),
('kristen', 'schaal', 'kristen_schaal.jpg'),
('bea',	'arthur', 'bea_arthur.jpg'),
('betty', 'white', 'betty_white.jpg'),
('rue',	'mcclanahan', 'rue_mcclanahan.jpg'),
('estelle',	'getty', 'estelle_getty.jpg'),
('terry', 'kiser', 'terry_kiser.jpg'),
('dan',	'aykroyd', 'dan_aykroyd.jpg'),
('eddie', '	murphy', 'eddie_murphy.jpg'),
('ralph', 'bellamy', 'ralph_bellamy.jpg'),
('don',	'ameche', 'don_ameche.jpg'),
('denholm', 'elliott', 'denholm_elliott.jpg')
;

-- program table
INSERT INTO program (title, yr_released, runtime, producer_id, format, program_rating, robins_rating, IMDb_id, wikipedia_url, img_url, summary, fun_fact)

VALUES (
    'Die Hard',
    1988, 
    2:12,
    '1',
    'live-action',
    'R',
    '5',
    'tt0095016',
    'https://en.wikipedia.org/wiki/Die_Hard',
    'Die_Hard_poster.jpg',
    "New York City policeman John McClane (Bruce Willis) is visiting his estranged wife (Bonnie Bedelia) and two daughters on Christmas Eve. He joins her at a holiday party in the headquarters of the Japanese-owned business she works for. But the festivities are interrupted by a group of terrorists who take over the exclusive high-rise, and everyone in it. Very soon McClane realizes that there's no one to save the hostages -- but him.",
    "The role of Hans Gruber was Alan Rickman's first film role."
),
(
    'Rudolph the Red-Nosed Reindeer',
    1964,
    0:47,
    '2',
    'stop-motion',
    'NR',
    '5',
    'tt0058536',
    'https://en.wikipedia.org/wiki/Rudolph_the_Red-Nosed_Reindeer_(TV_special)',
    'Rudolph_1964_poster.jpg',
    "A young reindeer Rudolph lives at the North Pole. His father is one of Santa's reindeer and it is expected that Rudolph will eventually be one too. However, he has a feature which is a setback and causes him to be ostracized: his red nose.",
    "The special was published (and continues to be aired) with an invalid copyright notice, which identifies the year of publication as 1164 instead of the intended 1964 due to an omission of an M digit in the Roman numeral."
),
(
    'Trailer Park Boys Xmas Special',
    2004,
    0:57,
    '3',
    'live-action',
    'NR',
    '5',
    'tt0439856',
    null,
    'Trailer_Park_Boys_Xmas_Special_poster.jpg',
    "It's Christmas 1997.",
    "This television special is a prequel to Trailer Park Boys (2001) but it shows Bubbles living in a garden shed which he didn't move into until his shack burned down in season two."
),
(
    'How the Grinch Stole Christmas',
    2000,
    1:44,
    '4',
    'live-action',
    'PG',
    '5',
    'tt0170016',
    'https://en.wikipedia.org/wiki/How_the_Grinch_Stole_Christmas_(2000_film)',
    'How_the_Grinch_Stole_Christmas_2000_poster.jpg',
    "The 2000 film How the Grinch Stole Christmas is about the green, grumpy Grinch who lives on Mount Crumpit and hates Christmas because of childhood trauma. ",
    "The role of Max was played by six different mixed-breed shelter rescues, with the main two dogs being Kelley and Chip."
),
(
    'The Polar Express',
    2004,
    1:40,
    '5',
    'motion-capture',
    'G',
    '4',
    'tt0338348',
    'https://en.wikipedia.org/wiki/The_Polar_Express_(film)',
    'The_Polar_Express_(2004)_poster.jpg',
    "The Polar Express is a story about a doubting young boy who takes a magical train ride to the North Pole on Christmas Eve. It's based on the children's book by Chris VanAllsburg.",
    "Tom Hanks voiced and portrayed six different characters in the film: the Conductor, Santa Claus, the Hero Boy's Father, the Hobo, the Scrooge puppet, and the Hero Boy."
),
(
    'Gremlins',
    1984,
    1:46,
    '6',
    'live-action',
    'PG',
    '5',
    'tt0087363',
    'https://en.wikipedia.org/wiki/Gremlins',
    'Gremlins_poster.jpg',
    "A gadget salesman is looking for a special gift for his son and finds one at a store in Chinatown. He gets a lot more than he bargained for.",
    "Gizmo's voice was performed by Howie Mandel."
),
(
    'A Charlie Brown Christmas',
    1965,
    0:25,
    '7',
    'animation',
    'G',
    '5',
    'tt0059026',
    'https://en.wikipedia.org/wiki/A_Charlie_Brown_Christmas',
    'Charlie_Brown_Christmas_poster.jpg',
    "A television special where a depressed Charlie Brown, disillusioned by the commercialism of Christmas, takes on directing the school's Christmas pageant to find the holiday's true meaning.",
    "The show's depiction of a sad, pathetic aluminum Christmas tree was so impactful that it contributed to the virtual elimination of aluminum tree sales after 1965."
),
(
    "National Lampoon's Christmas Vacation",
    1989,
    1:37,
    '8',
    'live-action',
    'PG-13',
    '5',
    'tt0097958',
    'https://en.wikipedia.org/wiki/National_Lampoon%27s_Christmas_Vacation',
    'National_Lampoon_Xmas_poster.jpg',
    "As the holidays approach, Clark Griswold wants to have a perfect family Christmas, so he tries to make sure everything is in order, but things go awry quickly.",
    "The Griswold's yuppie neighbors' house is the same house used as the Murtaugh house in Lethal Weapon and has appeared in every Vacation film."
),
(
    'The Nightmare Before Christmas',
    1993,
    1:16,
    '9',
    'stop-motion',
    'PG',
    '5',
    'tt0107688',
    'https://en.wikipedia.org/wiki/The_Nightmare_Before_Christmas',
    'The_Nightmare_Before_Christmas_poster.jpg',
    "Tim Burton's The Nightmare Before Christmas tells the story of Jack Skellington, the king of Halloween Town, who stumbles upon Christmas Town and schemes to take over the holiday.",
    "The film was shot at 24 frames per second, meaning the animators had to make 24 individual poses for just one second of footage."
),
(
    'Elf',
    2003,
    1:37,
    '10',
    'live-action',
    'PG',
    '2',
    'tt0319343',
    'https://en.wikipedia.org/wiki/Elf_(film)',
    'Elf_poster.jpg',
    "Buddy was accidentally transported to the North Pole as a toddler and raised to adulthood among Santa's elves. Unable to shake the feeling that he doesn't fit in, the adult Buddy travels to New York to find his real father.",
    "Peter Billingsley, who played Ralphie in A Christmas Story, has a cameo as an elf named Ming Ming. "
),
(
    'A Christmas Story',
    1983,
    1:33,
    '11',
    'live-action',
    'PG',
    'NA',
    'tt0085334',
    'https://en.wikipedia.org/wiki/A_Christmas_Story',
    'A_Christmas_Story_poster.jpg',
    "In the 1940s, a young boy named Ralphie Parker attempts to convince his parents, teacher, and Santa Claus that a Red Ryder Range 200 Shot BB gun really is the perfect Christmas gift.",
    "To create the snowy winter scenes, special effects used potato flakes for falling snow and shredded vinyl for ground cover, since Cleveland experienced a record warm winter during production. "
),
(
    'Home Alone',
    1990,
    1:43,
    '1',
    'live-action',
    'PG',
    '5',
    'tt0099785',
    'https://en.wikipedia.org/wiki/Home_Alone',
    'Home_Alone_poster.jpg',
    "When bratty 8-year-old Kevin McCallister (Macaulay Culkin) acts out the night before a family trip to Paris, his mother (Catherine O'Hara) makes him sleep in the attic. After the McCallisters mistakenly leave for the airport without Kevin, he awakens to an empty house and assumes his wish to have no family has come true.",
    "The photo of Buzz's girlfriend was actually a picture of a boy."
),
(
    'A Christmas Carol',
    1951,
    1:26,
    '12',
    'live-action',
    'NR',
    'NA',
    'tt0044008',
    'https://en.wikipedia.org/wiki/Scrooge_(1951_film)',
    'A_Christmas_Carol_1951_poster.jpg',
    "Ebenezer Scrooge, a curmudgeonly, miserly businessman, has no time for sentimentality and largely views Christmas as a waste of time. However, this Christmas Eve, he will be visited by three spirits who will show him the error of his ways.",
    "In one scene, two crew members are visible in the reflection of a mirror when Scrooge looks at himself. "
),
(
   'Edward Scissorhands',
   1990,
   1:45,
   '9',
   'live-action',
   'PG-13',
    '5',
    'tt0099487',
    'https://en.wikipedia.org/wiki/Edward_Scissorhands',
    'Edward_Scissorhands_poster.jpg',
    " It tells the story of an unfinished artificial humanoid who has scissor blades instead of hands, is taken in by a suburban family, and falls in love with their teenage daughter.",
    "Johnny Depp only speaks 169 words in the entire movie."
),
(
    'While You Were Sleeping',
    1995,
    1:43,
    '13',
    'live-action',
    'PG',
    'NA',
    'tt0114924',
    'https://en.wikipedia.org/wiki/While_You_Were_Sleeping_(film)',
    'While_Sleeping_poster.jpg',
    "A Subway clerk falls for a comatose man's brother.",
    "The line, 'I don't drink anymore. I don't drink any less either!' was delivered by Glynis Johns, who had previously said the same line 31 years earlier in the TV show Bewitched. "
),
(
    'Scrooged',
    1988,
    1:41,
    '14',
    'live-action',
    'PG-13',
    'NA',
    'tt0096061',
    'https://en.wikipedia.org/wiki/Scrooged',
    'Scrooged_poster.jpg',
    "Based on the 1843 novella A Christmas Carol by Charles Dickens, Scrooged is a modern retelling that follows Bill Murray as Frank Cross, a cynical and selfish television executive who is visited by a succession of ghosts on Christmas Eve intent on helping him regain his Christmas spirit.",
    " At the end of the movie, when everyone is singing, Murray yells, "Feed me, Seymour!" This is a direct reference to the giant man-eating plant from one of his earlier films, Little Shop of Horrors. "
),
(
    '"Black Mirror" White Christmas (S2.E4)',
    2014,
    1:13,
    '15',
    'live-action',
    'MA',
    '5',
    'tt3973198',
    'https://en.wikipedia.org/wiki/White_Christmas_(Black_Mirror)',
    'Black_Mirror_White_Christmas_poster.jpg',
    "The episode explores three stories told by Matt (Jon Hamm) and Joe (Rafe Spall) from a remote cabin on Christmas Day.",
    "It is an extended Christmas special filled with Easter eggs referencing all previous episodes because creator Charlie Brooker considered this his final Black Mirror episode at the time, but then Netflix picked up the series."
),
(
    'Jack Frost',
    1998,
    1:41,
    '16',
    'live-action',
    'PG',
    '5',
    'tt0141109',
    'https://en.wikipedia.org/wiki/Jack_Frost_(1998_film)',
    'Jack_Frost_poster.jpg',
    "A father who can't keep his promises is killed in a car accident. One year later, he returns as a snowman who has the final chance to put things right with his son before he is gone forever.",
    "George Clooney was originally attached to play Jack Frost, but he left to star in Batman & Robin (1997)."
),
(
    'How the Grinch Stole Christmas!',
    1966,
    0:26,
    '11',
    'animation',
    'G',
    'NA',
    'tt0060345',
    'https://en.wikipedia.org/wiki/How_the_Grinch_Stole_Christmas!_(TV_special)',
    'How_the_Grinch_Stole_Christmas_1966_poster.jpg',
    'A grumpy hermit hatches a plan to steal Christmas from the Whos of Whoville.',
    'An ironic sponsor for the anti-consumerist special was a bank.'
),
(
    'Frosty the Snowman',
    1969,
    0:25,
    '17',
    'animation',
    'NR',
    '5',
    'tt0064349',
    'https://en.wikipedia.org/wiki/Frosty_the_Snowman_(TV_special)',
    'Frosty_the_Snowman_poster.jpg',
    "A living snowman and a little girl struggle to elude a greedy magician who is after the snowman's magic hat.",
    "Jimmy Durante narrated the special in his final film role."
),
(
    "It's a Wonderful Life",
    1946,
    2:10,
    '18',
    'live-action',
    'PG',
    'NA',
    'tt0038650',
    'https://en.wikipedia.org/wiki/It%27s_a_Wonderful_Life',
    'Its_a_Wonderful_Life_1946_poster.jpg',
    'An angel is sent from Heaven to help a desperately frustrated businessman see the value of his own life.',
    'The FBI issued a memo in 1947 expressing concern that the film might be a form of "Communist infiltration of the motion picture industry". '
),
(
    'A Christmas Carol',
    1984,
    1:40,
    '19',
    'live-action',
    'PG',
    'NA',
    'tt0087056',
    'https://en.wikipedia.org/wiki/A_Christmas_Carol_(1984_film)',
    'A_Christmas_Carol_1984_poster.jpg',
    "A bitter old miser who rationalizes his uncaring nature learns real compassion when three spirits visit him on Christmas Eve.",
    "The film was shot almost entirely on location in Shrewsbury, England, and much of the set, including a prop gravestone, is still there."
),
(
    'A Christmas Carol',
    2009,
    1:36,
    '20',
    'motion-capture',
    'PG',
    '4',
    'https://en.wikipedia.org/wiki/A_Christmas_Carol_(2009_film)',
    'A_Chistmas_Carol_2009_poster.jpg',
    "Ebenezer Scrooge, a miserly old moneylender, is visited by three Christmas spirits on Christmas Eve. Scrooge embarks on a journey of self-redemption to mend his miserly ways.",
    "The film includes an Easter egg connecting it to another Robert Zemeckis Christmas film, The Polar Express. A similar Scrooge puppet appears in that movie."
),
(
    '"Bobs Burgers" The Plight Before Christmas (S13.E10)',
    2022,
    0:21,
    '21',
    'animation',
    'PG',
    '5',
    'tt23708680',
    'https://en.wikipedia.org/wiki/The_Plight_Before_Christmas',
    'The_Plight_Before_Christmas_poster.jpg',
    "Bob and Linda try to attend all the kids' holiday performances at the same time.",
    'The "Burger of the Day" is "The Pineapple on 34th Street Burger," a play on the movie title Miracle on 34th Street.'
),
(
    '"The Golden Girls" Twas the Nightmare Before Christmas (S2.E11)',
    1986,
    0:30,
    '22',
    'live-action',
    'PG',
    '5',
    'tt0589703',
    'https://en.wikipedia.org/wiki/The_Golden_Girls_season_2',
    'Golden_Girls_Twas_Night_poster.jpg',
    "The girls all plan to visit their respective families for Christmas, but their plans are ruined when they are held hostage by a man dressed as Santa Claus at the Grief Counseling Center.",
    'The "Men of Blanches Boudoir" calendar was not a genuine prop but a practical joke, with the prop department taking exaggerated, semi-nude photos of themselves for the calendar.'
),
(
    'Trading Places',
    1983,
    1:58,
    '23',
    'live-action',
    'R',
    '5',
    'tt0086465',
    'https://en.wikipedia.org/wiki/Trading_Places',
    'Trading_Places_poster.jpg',
    "The Duke brothers, Randolph and Mortimer, make a bet to prove that a person's environment is more important than their heredity.",
    "There were interesting cameos: Giancarlo Esposito of Breaking Bad fame portrayed the blink-and-you-missed-it role of Cellmate #2, Jim Belushi was in the gorilla costume, and Al Franken played a baggage handler."
)